### ISSUE TITLE
Wrong definition

### ISSUE THREAD

**Issue by Tazeg** [ybourque/Wikparser#2]
Trying to get definition for the french word "apanageras" with : 
http://www.igrec.ca/project-files/wikparser/wikparser.php?lang=fr&word=apanageras&query=def

Have a look at source code. There is a trailing : `</wikitext></parse></api>`

Same with words : agronomiques, aguichants, aguis, ajointant...

**Comment by ybourque** [comment]
You're not in fact getting the wrong definitions, just the impoverished ones provided by most dictionaries for inflected forms. Thus, "agronomiques" simply returns "Plural of agronomique" and a link to the uninflected form. Currently, I can see no foolproof way to return the definition for the uninflected form when querying the inflected one, given that Wiktionary includes the redirect within the definition tag like it would any other link to related terms.

**Comment by Tazeg** [comment]
Yes, those are right definitions. That's not the problem.
Please click on http://www.igrec.ca/project-files/wikparser/wikparser.php?lang=fr&word=apanageras&query=def
Then in the browser select "view source code page".
You will see HTML code, for some words like : agronomiques, aguichants, aguis, ajointant.
For other words like : table, aboyer.. there is no pollutant html code in the definition got.

**Comment by ybourque** [comment]
Yes, now I understand. This seems to happen if what you request (e.g. definition) is the final string in the data returned by the API. I've updated the extraction class to remove the API's XML tags.

Thanks for letting me know about this issue.
