### ISSUE TITLE
Add some improvements

### ISSUE THREAD

**Issue by pmjones** [ybourque/Wikparser#5]
Hi @ybourque and @quuuit --

I've been asked to use Wikparser for a client project, and they're going to pay me to add some improvements to it, if you are open to the idea. These are the suggestions:
- Remove die() in favor of throwing exceptions, and/or returning empty arrays in non-exceptional circumstances
- Convert class.*.php to ClassName.php to enable autoloading everywhere
- Make it so that one fetch from the API or the database can return all 5 queries in a single result.

I can accomplish those in about a day, along with maybe setting up some basic testing functionality, and submit the PR for your approval.

Any interest?

**Comment by ybourque** [comment]
Hello Paul,

No problem. The first two are quick changes, but the third will require a
bit more effort. In any case, have at it.

Yves

**Comment by pmjones** [comment]
Many thanks. I can't tell, should I make them here, or on the @quuuit repo?

**Comment by ybourque** [comment]
Hi Paul,

Let me check the repos this evening and get back to you then. I don't quite
recall what changes were made.

Best,
Yves

**Comment by quuuit** [comment]
Hi to all. I think you should use that repo, which is simpler extendable.

**Comment by pmjones** [comment]
@quuuit "That" repo, meaning which one?

**Comment by quuuit** [comment]
@pmjones I think Yves's, because i've changed some methods for my personal project needs.

**Comment by pmjones** [comment]
Got it; thanks.

As a side note, I see that the @ybourque composer.json names this project as "quuuit/wikparser" and Packagist points to the @quuuit repository -- should that be amended to point to @ybourque instead? Otherwise, that means dev-master changes to @ybourque won't be reflected through Composer.

**Comment by ybourque** [comment]
@pmjones @quuuit added the composer.json to the @ybourque repo, maybe as a copy from the forked repo. I've updated the properties. (I didn't originally include a composer.json file.)

**Comment by pmjones** [comment]
Excellent; I can register it on Packagist for you and set you as the owner, if you like, or you can do it yourself.

Thanks!

**Comment by ybourque** [comment]
Much appreciated if you did. I've never actually used Packagist.

**Comment by pmjones** [comment]
Hi @ybourque I'm getting started, and I notice that the namespaces are all `quuuit`. Is @quuuit the original author then, or what? I ask because the top-level namespace is generally (not always) the same as the vendor-name on the Composer package. Would it be acceptable to change it to `ybourque` (or something else), or do we prefer leaving it as it is?

**Comment by ybourque** [comment]
Hi @pmjones I'm the original author of this parser. @quuuit integrated the Wiktionary language parameters (which were originally simply in a separate class) into the main wikparser.php file and wrapped the result in a Wikparser class so as to make its integration into other projects easier (my original approach was as a standalone PHP app). Thanks for letting me know about the namespace situation.
