### ISSUE TITLE
The project is not working for me.; 

### ISSUE THREAD

**Issue by NadaBen** [ybourque/Wikparser#9]
Hello, I tried to use your project, i copied the folder in my wamp server, when i run , 
`http://localhost/Wikparser-master/Wikparser-master/wikparser.php?word=dog`  it gives me nothing..

and when i open language.config.php in the server, it gives me these errors:
`Notice:` Undefined variable: langCode in C:\wamp\www\Wikparser-master\Wikparser-master\language.config.php on line 24`  ...

and when i open test

Warning: require(C:\wamp\www\Wikparser-master\Wikparser-master/vendor/autoload.php): failed to open stream: No such file or directory in C:\wamp\www\Wikparser-master\Wikparser-master\tests\test.php on line 4

How to solve that please?

**Comment by ybourque** [comment]
Hi NadaBen,
Unfortunately, the parser no longer works as described in the ReadMe. PMJones made significant changes to the tool's functionality, which was then merged to the master. For the current version to work, you must install [Composer](https://getcomposer.org/).

If you wish to use the parser as it was originally intended, you can [download this earlier version](https://github.com/ybourque/Wikparser/tree/839e52d897ee0864ad2566923415ee6227759e51) and follow the instructions in the ReadMe file.

Regards,
YBourque
